### ISSUE TITLE
Landowner stats are not calculated correctly 

### ISSUE THREAD

**Issue by iholl** [WildlifeNV/huntnv-api#2]
Landowner stats add up to over 100% (see /hunts/679)

coverage should add up to 100

landownership:
     0:  
          area | 696723189.7963145
          coverage | 0.9999999999290886
          surface_mgmt_agency | "Federal (other)"
     1:
          area | 561194550.8153632
          coverage | 0.8054770660635425
          surface_mgmt_agency | "US Fish and Wildlife Service"

**Comment by kissmygritts** [comment]
@iholl, what units? 

This is because of the public land data. There are overlapping landowners.

**Comment by kissmygritts** [comment]
Use this link to alert users: https://www.usgs.gov/core-science-systems/science-analytics-and-synthesis/gap/science/pad-us-data-overview?qt-science_center_objects=0#qt-science_center_objects

**Comment by kissmygritts** [comment]
This won't be fixed here. It is a data issue that we will need to deal with later.
